services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      target: prod
      args:
        WWWUSER: ${WWWUSER}
        WWWGROUP: ${WWWGROUP}
    restart: always
    container_name: bangsalan-app
    working_dir: /var/www
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      COMPOSER_MEMORY_LIMIT: "-1"
      COMPOSER_CACHE_DIR: "/tmp/composer-cache"
    volumes:
      - .:/var/www:cached
      - .docker/php/supervisord.conf:/etc/supervisord.conf
      - .docker/php/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
      - composer_cache:/tmp/composer-cache
    depends_on:
      # - mysql
      - redis
    command: >
      sh -lc '
        if [ ! -f vendor/autoload.php ]; then
          echo "[app] Running composer install...";
          composer install --no-interaction --prefer-dist --optimize-autoloader;
        else
          echo "[app] vendor/ already exists, skipping composer install";
        fi
        chown -R www-data:www-data storage bootstrap/cache || true;
        exec supervisord -n -c /etc/supervisord.conf
      '
    networks:
      - external_net

  nginx:
    image: nginx:alpine
    container_name: bangsalan-nginx
    restart: always
    ports:
      - "8089:80"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - external_net

  # postgres:
  #   ...

  redis:
    image: redis:alpine
    container_name: bangsalan-redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - external_net

volumes:
  # pg_data:
  redis_data:
  composer_cache:

networks:
  external_net:
    external: true
